source 'https://rubygems.org'
gem 'mailcatcher', '0.5.12'

group :development do
  # Sass, Compass and extensions.
  gem 'sass', '~> 3.2.10'                    # Sass.
  gem 'sass-globbing', '~> 1.1.0'           # Import Sass files based on globbing pattern.
  gem 'compass', '~> 0.12.2'                 # Framework built on Sass.
  gem 'compass-validator', '~> 3.0.1'       # So you can `compass validate`.
  gem 'compass-normalize', '~> 1.4.3'       # Compass version of normalize.css.
  gem 'compass-rgbapng', '~> 0.2.1'         # Turns rgba() into .png's for backwards compatibility.
  gem 'susy', '~> 1.0.9'                    # Susy grid framework.
  gem 'singularitygs', '~> 1.1.2'           # Alternative to the Susy grid framework.
  gem 'toolkit', '~> 1.3.7'                 # Compass utility from the fabulous Snugug.
  gem 'breakpoint', '~> 2.0.6'              # Manages CSS media queries.
  gem 'oily_png', '~> 1.1.0'                # Faster Compass sprite generation.
  gem 'css_parser', '~> 1.3.4'              # Helps `compass stats` output statistics.

  # Guard
  gem 'guard', '~> 1.8.2'                   # Guard event handler.
  gem 'guard-compass', '~> 0.0.8'           # Compile on sass/scss change.
  gem 'guard-shell', '~> 0.5.1'             # Run shell commands.
  gem 'guard-livereload', '~> 1.4.0'        # Browser reload.
  gem 'yajl-ruby', '~> 1.1.0'               # Faster JSON with LiveReload in the browser.

  # Dependency to prevent polling. Setup for multiple OS environments.
  # Optionally remove the lines not specific to your OS.
  # https://github.com/guard/guard#efficient-filesystem-handling
  gem 'rb-inotify', '~> 0.9', :require => false      # Linux
  gem 'rb-fsevent', :require => false                # Mac OSX
  gem 'rb-fchange', :require => false                # Windows
end
